name: build

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - centos-8
          - ubuntu-1604
          - ubuntu-1804
          - ubuntu-2004
          # - ubuntu-2010
        arch:
          - linux/amd64
          - linux/arm64
        gcc:
          - 7.5.0
          - 8.3.0
          - 9.3.0
          - 10.1.0
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/buildx/${{ matrix.os }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: vesoft/third-party-build:${{ matrix.os }}
          push: false
          build-args: |
            USE_GCC_VERSIONS=${{ matrix.gcc }}
          secrets: |
            "ossutilconfig=${{ secrets.OSS_UTIL_CONFIG }}"
