name: build

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - centos-8
          - ubuntu-1604
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2010
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/buildx/${{ matrix.os }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: vesoft/third-party-build:${{ matrix.os }}
          push: false
          secrets: |
            "ossutilconfig=${{ secrets.OSS_UTIL_CONFIG }}"
